config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  resources :users, except: [:show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :houses do
    collection do
      post 'register_mortality', action: 'register_mortality'
    end
  end
  get 'dashboard', to: 'users#show', as: :dashboard

  get '*path', to: 'home#missing', as: :missed
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
# == Schema Information
#
# Table name: houses
#
#  id               :integer          not null, primary key
#  name             :string
#  code             :string
#  capacity         :integer
#  population       :integer
#  user_id          :integer
#  feed_consumption :float
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class House < ApplicationRecord
  belongs_to :user, -> { where(level: 2) }
  has_many :mortalities
  
  validates_presence_of :name
end

app/models/mortality.rb
# == Schema Information
#
# Table name: mortalities
#
#  id           :integer          not null, primary key
#  count        :integer
#  house_id     :integer
#  registrar_id :integer
#  cause        :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Mortality < ApplicationRecord
  validates_presence_of :count, :cause
  validates :cause, length: { minimum: 50 }

  belongs_to :house
  belongs_to :registrar, class_name: 'User'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string
#  name            :string
#  password_digest :string
#  level           :integer          default(0), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, presence: true
  validates :email, uniqueness: true
  validates_format_of :email, with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/

  has_secure_password

  has_many :houses
  has_many :mortalities

  after_create :hierarchy, :is_admin?

  def hierarchy
    return 'Admin' if self.level == 2
    return 'Manager' if self.level == 1
    return 'Supervisor'
  end

  def is_admin?
    self.level == 2
  end
end

app/controllers/api/v1/houses_controller.rb
module Api
  module V1
    class HousesController < ApplicationController
      def index
        houses = House.all

        render json: houses, status: :ok
      end

      def show
        house = House.find_by(id: params[:id])

        if house
          render json: house, status: :ok
        else
          render status: :not_found
        end
      end

      def create
        house = House.new(house_params)

        if house.save
          render json: house, status: :created
        else
          render json: house.errors, status: :unprocessable_entity
        end
      end

      def update
        house = House.find_by(id: params[:id])
        house.update_attributes(house_params)

        if house.save
          render json: house, status: :no_content
        else
          render json: house.errors, status: :unprocessable_entity
        end
      end

      def destroy
        house = House.find_by(id: params[:id])

        if house && house.destroy
          render json: house, status: :no_content
        else
          render status: :not_found
        end
      end

      private

      def house_params
        params.permit(
          :name, :code, :capacity, :stage, :admin_id
        )
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionHandler
  include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render 'users/dashboard' if current_user
  end

  def missing
    render(file: "#{Rails.root}/public/404.html", status: 404)
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :login_required!
  def index
    @houses = House.all
  end

  def new
    @house = current_user.houses.new
  end

  def create
    @house = current_user.houses.new(house_params)

    if @house.save
      redirect_to house_path(@house.id)
    else
      render :new
    end
  end

  def show
    @house = House.find_by(id: params[:id])
    @mortality = Mortality.new

    redirect_to '/404.html' if @house.nil?
  end

  def register_mortality
    @house = House.find_by(id: params[:mortality][:house_id])
    @mortality = Mortality.new(
      registrar_id: current_user.id, house_id: @house.id,
      count: params[:mortality][:count], cause: params[:mortality][:cause]
    )

    if @mortality.save
      handler = MortalityHandler.new(@mortality.count, @house.id)
      if handler.remove_dead_birds!
        @house.save
        redirect_to house_path(params[:mortality][:house_id])
      end
    end
  end

  private

  def house_params
    params.require(:house).permit(
      :name, :code, :capacity, :population, :feed_consumption
    )
  end

  def mortality_params
    params.require(:mortality).permit(
      :cause, :count, :registrar_id, :house_id
    )
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash.now[:success] = 'Successfully signed in'
      sign_in user
      session[:id] = user.id
      redirect_to dashboard_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'home/index'
    end
  end

  def destroy
    sign_out if signed_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :login_required!
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to dashboard_path
    else
      render :new
      flash[:error] = 'Error occured'
    end
  end

  def show
    @user = User.find_by(id: params[:id])

    render 'users/dashboard'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    user_id = session[:user_id]
    @current_user ||= User.find_by(id: user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="general-forms">
  <div class="form-container col-md-4 col-sm-5 col-xs-7">
    <h3 class="login-detail">Login</h3>
    <%= form_for :session, url: sessions_path, html: { class: "signin card-panel" } do |f| %>
      <div class="form-entries">
        <%= f.email_field :email, placeholder: 'Enter your email', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.password_field :password, placeholder: 'Enter your password', class: 'form-control' %>
      </div>

      <div>
        <%= f.submit 'Login', class: 'general-button login-btn' %>
      </div>
    <% end %>
  </div>
</div>

app/views/houses/index.html.erb
<%= render 'layouts/header' %>

<div class="container">
  <h2>Pen Houses</h2>
  <p>Houses and their data</p>

  <%= pie_chart House.group(:name).sum(:population) %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Code</th>
        <th>Capacity</th>
        <th>Population</th>
        <th>Created By</th>
      </tr>
    </thead>
    <tbody>
      <% @houses.each do |house| %>
        <tr>
          <td><%= house.name %></td>
          <td><%= house.code %></td>
          <td><%= house.capacity %></td>
          <td><%= house.population %></td>
          <td><%= house.user.name %></td>
          <td><%= link_to 'details', house_path(house.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div> <%= link_to 'New House', new_house_path %> </div>
</div>

app/views/houses/new.html.erb
<%= render 'layouts/header' %>

<div class="general-forms house-form">
  <div class="form-container col-md-4 col-sm-5 col-xs-7">
    <h3 class="">Create new user</h3>
    <%= form_for @house, html: { class: "signin card-panel" } do |f| %>
      <div class="form-entries">
        <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.text_field :code, placeholder: 'Code', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.text_field :population, placeholder: 'Population', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.text_field :feed_consumption, placeholder: 'Feed Consumption', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.text_field :capacity, placeholder: 'Capacity', class: 'form-control' %>
      </div>

      <div>
        <%= f.submit 'Create House', class: 'general-button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/houses/show.html.erb
<%= render 'layouts/header' %>
<div>
  <nav class="house-nav">
    <ul>
      <li class="house-action active">Status</li>
      <li class="house-action">Feed</li>
      <li class="house-action">Mortality</li>
      <li class="house-action">Eggs</li>
      <li class="house-action">Finance</li>
      <li class="house-action">Tasks</li>
      <li class="house-action">Settings</li>
    </ul>
  </nav>

  <div class="status">
    <div>Mortality</div>
    <div>
      <% if @house.mortalities.any? %>
        <%= line_chart @house.mortalities.group_by_day(:created_at).sum(:count), discrete: true %>
      <% end %>
    </div>
  </div>

  <div class="mortality">
    <div>Register New Mortality</div>
    <div>
      <div class="general-forms mortality-form">
        <div class="form-container col-md-4 col-sm-5 col-xs-7">
          <h3 class="">Record new Mortality</h3>
          <%= form_for @mortality, url: register_mortality_houses_path, html: { class: "mortal card-panel" } do |f| %>

            <%= f.hidden_field :house_id, value: @house.id %>
            <div class="form-entries">
              <%= f.text_field :count, placeholder: 'How many birds Died?', class: 'form-control' %>
            </div>

            <div class="form-entries">
              <%= f.text_area :cause, placeholder: 'What is the likely cause', class: 'form-control' %>
            </div>

            <div>
              <%= f.submit 'Record Mortality', class: 'general-button mortal-btn' %>
            </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar">
  <div><%= link_to 'Home', root_path %></div>
  <div><%= link_to 'Sign Out', session_path(current_user.id), method: :delete %></div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BirdLay</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
          <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/dashboard.html.erb
<%= render 'layouts/header' %>

<div class = 'dashboard col-md-10', id = 'dashboard'>
  <div class='user-actions'><%= link_to 'Manage Houses', houses_path %></div>
  <div class='user-actions'><%= link_to 'Manage Users', users_path %></div>
  <div class='user-actions'><%= link_to 'Manage Users', users_path %></div>
  <div class='user-actions'><%= link_to 'Manage Users', users_path %></div>
<div>

app/views/users/index.html.erb
<%= render 'layouts/header' %>

<div class="container">
  <h2>Users</h2>
  <p>All house users</p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Level</th>
        <th>Population</th>
        <th>Created By</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.email %></td>
          <td><%= user.hierarchy %></td>
          <td><%=  %></td>
          <td><%=  %></td>
          <td><%= link_to 'details', '#' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New User', new_user_path %>
</div>

app/views/users/new.html.erb
<div class="general-forms login-form">
  <div class="form-container col-md-4 col-sm-5 col-xs-7">
    <h3 class="">Create new user</h3>
    <%= form_for @user, html: { class: "signin card-panel" } do |f| %>
      <div class="form-entries">
        <%= f.text_field :name, placeholder: 'New User Name', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.email_field :email, placeholder: 'New User Email', class: 'form-control' %>
      </div>

      <div class="form-entries">
        <%= f.password_field :password, placeholder: 'New User Password', class: 'form-control' %>
      </div>

      <div>
        <%= f.submit 'Create User', class: 'general-button login-btn' %>
      </div>
    <% end %>
  </div>
</div>